/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* "BSDI" */
/* #undef BSDI */

/* "FREEBSD" */
/* #undef FREEBSD */

/* "LINUX" */
#define LINUX 

/* "MACOS" */
/* #undef MACOS */

/* "OPENBSD" */
/* #undef OPENBSD */

/* Name of package */
#define PACKAGE "vulture"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* "SOLARIS" */
/* #undef SOLARIS */

/* Version number of package */
#define VERSION "0.9"
